### ISSUE TITLE
Unset attributes are empty strings not null

### ISSUE THREAD

**Issue by bjornharrtell** [michaelmgis/osmdata.xyz#14]
When playing around with osmdata.xyz as source for some large file tests using my format flatgeobuf I noted that unset attributes are empty strings not null which in my case results in a bit of bloat. I would assume it would be nicer and probably save space for GeoPackage also if they could be null instead.

**Comment by michaelmgis** [comment]
Thank you for feedback.
This is actually an implementation in [imposm](https://imposm.org/docs/imposm3/latest/mapping.html?highlight=null#string). 

A "empty string to null clean-up" is planned.

**Comment by michaelmgis** [comment]
After tests, my findings are the following:
- storage needed comparing GPKGs with _empty strings_ with _NULL values_ --> GPKGs with NULL values are 0.3% smaller

- processing time to replace empty string values by NULL --> it takes 10.000% more time (area of Bremen which is a german city was tested; 30 seconds VS. 50 minutes)

Since processing time is getting out of hand and leads to increasing costs (especially on a global scale), we should keep the default output of the processing tools. If you need NULL values, please process this by yourself after downloading.

**Comment by bjornharrtell** [comment]
Thanks for investigating.
