### ISSUE TITLE
Q: why are there two feature tables with line geometries?

### ISSUE THREAD

**Issue by justb4** [michaelmgis/osmdata.xyz#32]
Each GeoPackage contains four feature tables, one per geometry, e.g. for feature `<feature>`:

`point_EPSG4326_<feature>`,  `line_EPSG4326_<feature>`,  `multilinestring_EPSG4326_<feature>` and `multipolygon_EPSG4326_<feature>`.

My question is why is there both `line_EPSG4326_<feature>` and  `multilinestring_EPSG4326_<feature>`?
Quick research shows some overlap, for example `aerialway` with `name=Téléphérique de l'Aiguille du Midi 1` (long cable cart near Mont Blanc) has a `line` whose geometry is also contained in the `multilinestring` for that feature with same `name`. Or is there a feature-set in  `line_EPSG4326_<feature>`  that is not in `multilinestring_EPSG4326_<feature>`  and v.v.? 

Shouldn't `line` and `multilinestring` tables then be merged into a single `multilinestring`?

**Comment by michaelmgis** [comment]
Openstreetmap knows both line feature types. Depending on the mapper, Objects are mapped as line or multi line. Some map features are exclusively mapped as line and some as Multiline. Sometimes both types are used within the same map feature. Because everything is possible and nothing can be excluded, everything is kept. It's better to keep everything instead of missing something, because this project want to deliver the raw data in a ready to use geospatial data format.

The provided data contains the raw information. Filtering and geometry checks/repairs are necessary.

**Comment by justb4** [comment]
Ok thanks for the quick reply @michaelmgis !
