### ISSUE TITLE
thanks but incomplete?

### ISSUE THREAD

**Issue by Seandebasti** [michaelmgis/osmdata.xyz#36]
Hi Michael, thanks to your team for your project! I usually use overpass-api or Geofabrik to get the data I need.
I tested your data in a case where I mapped two features years ago with the same correct tag but in your data was only one feature available. I indicated this in differenz zip files. Is there any filter? thanks

**Comment by michaelmgis** [comment]
Hey!
Can you please specify the tag? Or do you mean a key? (key:tag)
The zip files contain features from each specific primary map/key feature of OSM. This is documented in the project description.
So it is possible that a tag, which is used with different keys is delivered in several zip files.

**Comment by Seandebasti** [comment]
Ah I understand, so in the case where tag could also be an key it would stored in a different zip file. 
e.g. landuse=industrial it is in landuse.zip, but industrial=* it would be in industrial.zip (if it is available)

**Comment by michaelmgis** [comment]
In case a key and tag is not represented by a primary map feature, since march 2021 there is a field at the end of each table named "other_tags". This is a hstore field which can be parsed. If you use QGIS you can explode the hstore field "other_tags" with the tool "explode hstore"

Then you can get landuse=industrial from the landuse zip file and industrial=* from the exploded hstore field.
